#! /bin/bash

unzip -oqq $1 -d /tmp/
cd /tmp/res

densities=( mdpi hdpi xhdpi xxhdpi xxxhdpi )

for density in "${densities[@]}"
do
    mv mipmap-$density/ic_launcher.png $2/drawable-$density &&
    echo Copied $density icon.
done
echo Done.
